In [2]:
from matplotlib import pyplot as plt
import numpy as np
import CTMRG_better_4 as CTM

def file(D, k):
    return './BH-cubicramp_3_' + str(D) + '_' + str(float(k)) + '_0.1'
def findzero(x,y):
    _t = []
    x = np.array(x)
    y = np.array(y)
    for i in range(x.shape[0]):
        _t.append(x**i)
    _t = np.array(_t).T
    a = np.linalg.solve(_t,y)
    y0 = np.array([1]+[0]*(x.shape[0]-1)) @ a
    return y0

In [108]:
for D in [4,6,8,10,12,14]:
    AA_trans, NN_trans, ks = [], [], []
    for k in np.arange(0,11,1):
        dirr = file(D, k)
        ts, AAs, NNs = [], [], []
        for i in range(0,1000):
            try:
                PEPS = dict(np.load(dirr + f'/PEPS_{i:05d}.npz'))
                print(PEPS['t'])
                ENV = dict(np.load(dirr + f'/RHOA_2_{i:05d}.npz'))
            except: continue
            ts.append(PEPS['t'])
            AAs.append(np.real_if_close(np.mean(ENV['vals2'][0]+ENV['vals2'][1])))
            NNs.append(np.real_if_close(np.mean(ENV['vals2'][2])))
        ks.append(k)
        if len(AAs) != 1:
            NN_trans.append(findzero(ts, NNs))
            AA_trans.append(findzero(ts, AAs))
        else:
            NN_trans.append(NNs[0])
            AA_trans.append(AAs[0])

    plt.plot(ks,AA_trans)

0
-0.15000000000000002


KeyboardInterrupt: 

In [4]:
## update of times :>

for D in [4,6,8,10,12,14]:
    for k in np.arange(0,110,10):
        print(D,k)
        dirr = file(D, k)
        SPECS = dict(np.load(dirr + '/SPECS.npz'))
        for i in range(0,1000):
            try:
                PEPS = dict(np.load(dirr + f'/PEPS_{i:05d}.npz'))
            except: continue
            np.savez(dirr + f'/peps_{i:05d}.npz',A=PEPS['A'],B=PEPS['B'],NTUerror=PEPS['NTUerror'],SVDUerror=PEPS['SVDUerror'],iter=i,dt=PEPS['dt'],J_exact=PEPS['J_exact'],J_average=PEPS['J_average'],U=PEPS['U'],NTUdelta=PEPS['NTUdelta'],t = i*PEPS['dt'])

4 0
4 10
4 20
4 30
4 40
4 50
4 60
4 70
4 80
4 90
4 100
6 0
6 10
6 20
6 30
6 40
6 50
6 60
6 70
6 80
6 90
6 100
8 0
8 10
8 20
8 30
8 40
8 50
8 60
8 70
8 80
8 90
8 100
10 0
10 10
10 20
10 30
10 40
10 50
10 60
10 70
10 80
10 90
10 100
12 0
12 10
12 20
12 30
12 40
12 50
12 60
12 70
12 80
12 90
12 100
14 0
14 10
14 20
14 30
14 40
14 50
14 60
14 70
14 80
14 90
14 100


In [64]:
for D in [4,6,8,10,12,14]:
    for k in np.arange(10,110,10):
        tmin = 9000
        ts = []
        inds = []
        for i in range(1, 10000):
            try: PEPS = dict(np.load(file(D,k) + f'/PEPS_{i:05d}.npz'))
            except: continue
            t = PEPS['t']
            inds.append(i)
            ts.append(t)
        print()
        print()
        print(file(D, k))
        inds_around = np.argsort(np.abs(np.array(ts)))[:5]
        print(inds_around)
        if len(inds_around) < 2: break
        t0 = (ts[inds_around[0]])
        t1 = (ts[inds_around[1]])
        if t0/(t1-t0) < 0.1: inds_around = inds_around[:1]
        else if t0/(t1-t0) < 0.1: inds_around = inds_around[:2]
        for i in inds_around:
            print(ts[i])



./BH-cubicramp_3_4_20.0_0.1
[6 7 5 8 4]
-2.220446049250313e-16


./BH-cubicramp_3_4_30.0_0.1
[12 11 13 10 14]
8.881784197001252e-16


./BH-cubicramp_3_4_40.0_0.1
[24 23 25 22 26]
1.7763568394002505e-15


./BH-cubicramp_3_4_50.0_0.1
[46 45 44 43 42]
-0.20000000000001705
-0.3000000000000167
-0.40000000000001634
-0.500000000000016
-0.6000000000000156


./BH-cubicramp_3_4_60.0_0.1
[77 76 75 74 73]
-1.9000000000000288
-2.0000000000000284
-2.100000000000028
-2.2000000000000277
-2.3000000000000274


./BH-cubicramp_3_4_70.0_0.1
[166 165 164 163 162]
-2.599999999999767
-2.6999999999997684
-2.79999999999977
-2.899999999999771
-2.9999999999997726


./BH-cubicramp_3_4_80.0_0.1
[306 305 304 303 302]
-7.799999999999571
-7.899999999999572
-7.999999999999574
-8.099999999999575
-8.199999999999577


./BH-cubicramp_3_4_90.0_0.1
[513 512 511 510 509]
-25.500000000002927
-25.60000000000292
-25.700000000002916
-25.80000000000291
-25.900000000002905


./BH-cubicramp_3_4_100.0_0.1
[777 776 775 774 773]
-75.

In [10]:
for k in np.arange(0, 110, 10):
    i_around = 3/2*2**(k/10)
    if i_around - np.floor(i_around) > 0.3:
        inds_around = [int(np.floor(i_around)),int(np.ceil(i_around))]
    else:
        inds_around = [int(np.round(i_around))]
    print(inds_around)

[1, 2]
[3]
[6]
[12]
[24]
[48]
[96]
[192]
[384]
[768]
[1536]


In [12]:
import os
## update of times :>

for D in [4,6,8,10,12,14]:
    for k in np.arange(0,110,10):
        dirr = file(D, k)
        print(dirr)
        for i in range(0,1000):
            try:
                os.remove(dirr + f'/peps_{i:05d}.npz')
            except:
                continue

./BH-cubicramp_3_4_0.0_0.1
./BH-cubicramp_3_4_10.0_0.1
./BH-cubicramp_3_4_20.0_0.1
./BH-cubicramp_3_4_30.0_0.1
./BH-cubicramp_3_4_40.0_0.1
./BH-cubicramp_3_4_50.0_0.1
./BH-cubicramp_3_4_60.0_0.1
./BH-cubicramp_3_4_70.0_0.1
./BH-cubicramp_3_4_80.0_0.1
./BH-cubicramp_3_4_90.0_0.1
./BH-cubicramp_3_4_100.0_0.1
./BH-cubicramp_3_6_0.0_0.1
./BH-cubicramp_3_6_10.0_0.1
./BH-cubicramp_3_6_20.0_0.1
./BH-cubicramp_3_6_30.0_0.1
./BH-cubicramp_3_6_40.0_0.1
./BH-cubicramp_3_6_50.0_0.1
./BH-cubicramp_3_6_60.0_0.1
./BH-cubicramp_3_6_70.0_0.1
./BH-cubicramp_3_6_80.0_0.1
./BH-cubicramp_3_6_90.0_0.1
./BH-cubicramp_3_6_100.0_0.1
./BH-cubicramp_3_8_0.0_0.1
./BH-cubicramp_3_8_10.0_0.1
./BH-cubicramp_3_8_20.0_0.1
./BH-cubicramp_3_8_30.0_0.1
./BH-cubicramp_3_8_40.0_0.1
./BH-cubicramp_3_8_50.0_0.1
./BH-cubicramp_3_8_60.0_0.1
./BH-cubicramp_3_8_70.0_0.1
./BH-cubicramp_3_8_80.0_0.1
./BH-cubicramp_3_8_90.0_0.1
./BH-cubicramp_3_8_100.0_0.1
./BH-cubicramp_3_10_0.0_0.1
./BH-cubicramp_3_10_10.0_0.1
./BH-cubicramp_3_10